linux-qcom-6.18: add patch to fix buildpaths QA issue
Add a patch to address build reproducibility QA error caused by
full path references in generated mach-types.h file:

ERROR: linux-qcom-6.18-r0 do_package_qa: QA Issue: File
/usr/src/debug/linux-qcom/6.18/arch/arm/include/generated/asm/mach-types.h
in package linux-qcom-src contains reference to TMPDIR [buildpaths]

The patch updates gen-mach-types to use basename() instead of FILENAME
to avoid embedding full paths in generated output.

Signed-off-by: Viswanath Kraleti <viswanath.kraleti@oss.qualcomm.com>